# Generated by Django 3.1 on 2020-09-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverresponse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMNOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Merchant_request_ID', models.CharField(max_length=50)),
                ('Checkout_request_ID', models.CharField(max_length=20)),
                ('Result_code', models.IntegerField()),
                ('Result_desc', models.CharField(max_length=120)),
                ('Ammount', models.FloatField()),
                ('Mpesa_receipt_number', models.CharField(max_length=20)),
                ('Transaction_date', models.DateTimeField()),
                ('Phone_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Lipanampesa',
        ),
    ]
