# Generated by Django 3.1 on 2020-09-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverresponse', '0003_auto_20200903_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmnonline',
            name='Checkout_requestID',
        ),
    ]
