# Generated by Django 3.1 on 2020-09-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namecomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('name', models.TextField(blank=True)),
            ],
        ),
    ]
